### <center> Name: Faiza Siddiqui </center>
### <center> 25-09-2021</center>
### <center> Q-learning </center> 

## An introduction to Q-Learning: Reinforcement Learning



### Before we start, what is Q-Learning?

### As kids, you must have solved maze problems, in which an animal finds its way through the maze. In reinforcement learning also similar kinds of steps are going around, that is an agent will learn how to pick up the paths. 
### Q-learning is nothing but a reinforcement learning algorithm to learn the value of an action in a particular state. The 'Q' in Q-learning refers to the quality. So we always look for the optimal(best) path to reach our goal. Quality here represents how useful a given action is in gaining some future reward. 
### Q-Learning has 3 major components : State, Action & Reward

![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTp2zGHxl4g3C5w-lU5TnaiHvKysotpiwNrRIh8SViSXr1nohsh-lJINPqVXC1C7-0pxdQ&usqp=CAU)

- State refers to the current position of an agent in an environment 

- Action is the step taken by the agent when the agent is in a particular state

- For every action, the agent will get a positive or negative reward. Reward function is, R: S X A → R

### Environment

##### In our example the environment is shown below, it is a guitar building factory with 9 different locations that agent can be in

![](https://i.ibb.co/c8LXj7X/Capture.png)

<center>The environment</center>

#### In the above environment, L6 is the end-goal of the agent, with top-priority location

### Agents

##### The agents, in this case, are the robots.

### States

##### States are the locations in which a particular robot can be present at any given time. We have mapped the location codes to numbers, since that is easier for machines to understand.

![](https://blog.floydhub.com/content/images/2019/05/image-1.png)

### Actions

#### Actions are direct locations to go from the states. 

![](https://blog.floydhub.com/content/images/2019/05/image-2.png)

### With the basic understanding clear, let's start the implementation

In [29]:
import numpy as np

#### We are defining the states

In [30]:
location_to_state = {
    'L1' : 0,
    'L2' : 1,
    'L3' : 2,
    'L4' : 3,
    'L5' : 4,
    'L6' : 5,
    'L7' : 6,
    'L8' : 7,
    'L9' : 8
}

#### We are now defining the actions

In [31]:
# Define the actions
actions = [0,1,2,3,4,5,6,7,8]

### Q-table 

##### While running the algorithm, there are multiple paths that an agent can take. We can find the best paths for the agent with the help of a table called Q-Table. 

![](https://i.ibb.co/k4kgnQS/Capture.png)

<center>Rewards' table</center>

##### Rewards

#### With the help of the table above we can now define the rewards matrix

In [32]:
# Define the rewards
rewards = np.array([[0,1,0,0,0,0,0,0,0],
              [1,0,1,0,0,0,0,0,0],
              [0,1,0,0,0,1,0,0,0],
              [0,0,0,0,0,0,1,0,0],
              [0,1,0,0,0,0,0,1,0],
              [0,0,1,0,0,0,0,0,0],
              [0,0,0,1,0,0,0,1,0],
              [0,0,0,0,1,0,1,0,1],
              [0,0,0,0,0,0,0,1,0]])

In [33]:
# Mapping indices to locations
state_to_location = dict((state,location) for location, state in location_to_state.items())

The following function is going to take two arguments: 

- starting location in the warehouse and 
- end location in the warehouse respectively 

It will return the optimal route for reaching the end location from the starting location in the form of an ordered list (containing the letters).

#### Before writing a helper function, let's learn about two parameters of Q-Learning algorithm - ɑ (learning rate) and 𝜸 (discount factor)

#### alpha(ɑ) is the learning rate which controls how quickly the robot adopts to the random changes imposed by the environment

In [34]:
#### Initialize parameters

gamma = 0.75 # Discount factor 
alpha = 0.9 # Learning rate 

##### The formula for Q-learning is given below

![](https://randomant.net/the-algorithm-behind-the-curtain-understanding-how-machines-learn-with-q-learning/q_learning_algorithm_2.gif)

The following function is going to take two arguments: 

- starting location in the warehouse and 
- end location in the warehouse respectively 

It will return the optimal route for reaching the end location from the starting location in the form of an ordered list (containing the letters).

In [35]:
def get_optimal_route(start_location,end_location):
    
    # Copy the rewards matrix to new Matrix
    
    new_rewards = np.copy(rewards)
    
    # Get the ending state corresponding to the ending location as given
    end_state = location_to_state[end_location]
    
    # With the above information automatically set the priority of the given ending state to the highest one
    new_rewards[end_state, end_state] = 999

    # -----------Q-Learning algorithm-----------
   
    # Initializing the Q-Table with all 0 values
    Q = np.array(np.zeros([9,9]))

    # Q-Learning process
    for i in range(1000):
        
        # Pick up a state randomly
        current_state = np.random.randint(0,9) 
        
        # For traversing through the neighbor locations in the maze
        workable_actions = []
        
        # Iterate through the new rewards matrix and get the actions > 0
        for j in range(9):
            if (new_rewards[current_state,j] > 0):
                workable_actions.append(j)
                
        # Pick an action randomly from the list of playable actions leading us to the next state
        next_state = np.random.choice(workable_actions)
        
        # Compute the temporal difference
        # The action here exactly refers to going to the next state
        # Temporal Difference is
        TemporalDifference = new_rewards[current_state,next_state] + gamma * Q[next_state, np.argmax(Q[next_state,])] - Q[current_state,next_state]
        
        # Update the Q-Value using the Bellman equation
        Q[current_state,next_state] += alpha * TemporalDifference

    # Initialize the optimal route with the starting location
    route = [start_location]
    
    # We do not know about the next location yet, so initialize with the value of starting location
    next_location = start_location
    
    # We don't know about the exact number of iterations needed to reach to the final location hence while loop will be a good choice for iteratiing
    while(next_location != end_location):
        
        # Fetch the starting state
        starting_state = location_to_state[start_location]
        
        # Fetch the highest Q-value pertaining to starting state
        next_state = np.argmax(Q[starting_state,])
        
        # We got the index of the next state. But we need the corresponding letter. 
        next_location = state_to_location[next_state]
        route.append(next_location)
        
        # Update the starting location for the next iteration
        start_location = next_location
    
    return route

### Now let's test our function

In [36]:
print(get_optimal_route('L9', 'L1'))

['L9', 'L8', 'L5', 'L2', 'L1']


In [39]:
print(get_optimal_route('L7', 'L3'))

['L7', 'L8', 'L5', 'L2', 'L3']


# Another Example

### Now imagine the robot is in another such guitar company. The picture of which is given below.

#### States
States are all of the possible locations within the guitar company. black boxes are for storing, whereas other locations are for the agent to move around. The **green square** is our high priority area. 
The black and green squares are **terminal states**!

![warehouse map](https://www.danielsoper.com/teaching/img/08-warehouse-map.png)

The states can be shown with a matrix of 11 rows and same number of columns.

Credits to Dr. Daniel Soper for this example of Q-learning. My intention to put this example here is to just show that I did understand this example as well and I also tried to look at many other examples.
https://www.youtube.com/watch?v=__t2XRxXGxI

In [40]:
#define the shape of the environment (i.e., its states)
environment_rows = 11
environment_columns = 11

In [41]:
#Create a 3D numpy array to hold the current Q-values for each state and action pair: Q(s, a) 
#The array contains 11 rows and 11 columns (to match the shape of the environment), as well as a third "action" dimension.
#The "action" dimension consists of 4 layers that will allow us to keep track of the Q-values for each possible action in
#each state (see next cell for a description of possible actions). 
#The value of each (state, action) pair is initialized to 0.
q_values = np.zeros((environment_rows, environment_columns, 4))

#### Actions
There are four available directions: Up, Down, Right, Left

In [42]:
#define actions
#numeric action codes: 0 = up, 1 = right, 2 = down, 3 = left
actions = ['up', 'right', 'down', 'left']

#### Rewards

Negative rewards (i.e., **punishments**) are used for all states except the goal.

![warehouse map](https://www.danielsoper.com/teaching/img/08-warehouse-map-rewards.png)


#### Creating a 2D numpy array to hold the rewards for each state

In [45]:
#The array contains 11 rows and 11 columns as discussed above, and each value is initialized to -100

rewards = np.full((environment_rows, environment_columns), -100.)
rewards[0, 5] = 100. #set the reward for the packaging area (i.e., the goal) to 100

#define aisle that is white boxes for rows 1 through 9 as shown in figure above
aisles = {} #store locations in a dictionary
aisles[1] = [i for i in range(1, 10)] 
aisles[2] = [1, 7, 9]
aisles[3] = [i for i in range(1, 8)]
aisles[3].append(9)
aisles[4] = [3, 7]
aisles[5] = [i for i in range(11)]
aisles[6] = [5]
aisles[7] = [i for i in range(1, 10)]
aisles[8] = [3, 7]
aisles[9] = [i for i in range(11)]

##### set the rewards for all white boxes

In [47]:
for row_index in range(1, 10):
  for column_index in aisles[row_index]:
    rewards[row_index, column_index] = -1.

##### print rewards matrix

In [48]:
for row in rewards:
  print(row)

[-100. -100. -100. -100. -100.  100. -100. -100. -100. -100. -100.]
[-100.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1. -100.]
[-100.   -1. -100. -100. -100. -100. -100.   -1. -100.   -1. -100.]
[-100.   -1.   -1.   -1.   -1.   -1.   -1.   -1. -100.   -1. -100.]
[-100. -100. -100.   -1. -100. -100. -100.   -1. -100. -100. -100.]
[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
[-100. -100. -100. -100. -100.   -1. -100. -100. -100. -100. -100.]
[-100.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1. -100.]
[-100. -100. -100.   -1. -100. -100. -100.   -1. -100. -100. -100.]
[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
[-100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100.]


### Define Helper Functions

##### Function if the specified location is a terminal state

In [52]:
def is_terminal_state(current_row_index, current_column_index):
  #if the reward for this location is -1, then it is not a terminal state (i.e., it is a 'white square')
  if rewards[current_row_index, current_column_index] == -1.:
    return False
  else:
    return True

#### Function that will choose a random, non-terminal starting location

In [53]:
def get_starting_location():
  #get a random row and column index
  current_row_index = np.random.randint(environment_rows)
  current_column_index = np.random.randint(environment_columns)
  #continue choosing random row and column indexes until a non-terminal state is identified
  #(i.e., until the chosen state is a 'white square').
  while is_terminal_state(current_row_index, current_column_index):
    current_row_index = np.random.randint(environment_rows)
    current_column_index = np.random.randint(environment_columns)
  return current_row_index, current_column_index

#### Define an algorithm that will choose which action to take 

In [56]:
def get_next_action(current_row_index, current_column_index, epsilon):
  #if a randomly chosen value between 0 and 1 is less than epsilon, 
  #then choose the most promising value from the Q-table for this state.
  if np.random.random() < epsilon:
    return np.argmax(q_values[current_row_index, current_column_index])
  else: #choose a random action
    return np.random.randint(4)

##### Define a function that will get the next location based on the chosen action


In [61]:
def get_next_location(current_row_index, current_column_index, action_index):
  new_row_index = current_row_index
  new_column_index = current_column_index
  if actions[action_index] == 'up' and current_row_index > 0:
    new_row_index -= 1
  elif actions[action_index] == 'right' and current_column_index < environment_columns - 1:
    new_column_index += 1
  elif actions[action_index] == 'down' and current_row_index < environment_rows - 1:
    new_row_index += 1
  elif actions[action_index] == 'left' and current_column_index > 0:
    new_column_index -= 1
  return new_row_index, new_column_index

##### Define a function that will get the shortest path between any location within the warehouse that the robot is allowed to travel and the item packaging location.

In [62]:
def get_shortest_path(start_row_index, start_column_index):
  #return immediately if this is an invalid starting location
  if is_terminal_state(start_row_index, start_column_index):
    return []
  else: #if this is a 'legal' starting location
    current_row_index, current_column_index = start_row_index, start_column_index
    shortest_path = []
    shortest_path.append([current_row_index, current_column_index])
    #continue moving along the path until we reach the goal (i.e., the item packaging location)
    while not is_terminal_state(current_row_index, current_column_index):
      #get the best action to take
      action_index = get_next_action(current_row_index, current_column_index, 1.)
      #move to the next location on the path, and add the new location to the list
      current_row_index, current_column_index = get_next_location(current_row_index, current_column_index, action_index)
      shortest_path.append([current_row_index, current_column_index])
    return shortest_path

#### Training Agent

In [63]:
#define training parameters
epsilon = 0.9 #the percentage of time when we should take the best action (instead of a random action)
discount_factor = 0.9 #discount factor for future rewards
learning_rate = 0.9 #the rate at which the AI agent should learn

#run through 1000 training episodes
for episode in range(1000):
  #get the starting location for this episode
  row_index, column_index = get_starting_location()

  #continue taking actions (i.e., moving) until we reach a terminal state
  #(i.e., until we reach the item packaging area or crash into an item storage location)
  while not is_terminal_state(row_index, column_index):
    #choose which action to take (i.e., where to move next)
    action_index = get_next_action(row_index, column_index, epsilon)

    #perform the chosen action, and transition to the next state (i.e., move to the next location)
    old_row_index, old_column_index = row_index, column_index #store the old row and column indexes
    row_index, column_index = get_next_location(row_index, column_index, action_index)
    
    #receive the reward for moving to the new state, and calculate the temporal difference
    reward = rewards[row_index, column_index]
    old_q_value = q_values[old_row_index, old_column_index, action_index]
    temporal_difference = reward + (discount_factor * np.max(q_values[row_index, column_index])) - old_q_value

    #update the Q-value for the previous state and action pair
    new_q_value = old_q_value + (learning_rate * temporal_difference)
    q_values[old_row_index, old_column_index, action_index] = new_q_value

print('Training done!')

Training done!


## Get Shortest Paths
Now that the AI agent has been fully trained, we can see what it has learned by displaying the shortest path between any location in the warehouse where the robot is allowed to travel and the item packaging area.

![warehouse map](https://www.danielsoper.com/teaching/img/08-warehouse-map.png)

Run the code cell below to try a few different starting locations!

In [59]:
#display a few shortest paths
print(get_shortest_path(3, 9)) #starting at row 3, column 9
print(get_shortest_path(5, 0)) #starting at row 5, column 0
print(get_shortest_path(9, 5)) #starting at row 9, column 5

[[3, 9], [2, 9], [1, 9], [1, 8], [1, 7], [1, 6], [1, 5], [0, 5]]
[[5, 0], [5, 1], [5, 2], [5, 3], [4, 3], [3, 3], [3, 2], [3, 1], [2, 1], [1, 1], [1, 2], [1, 3], [1, 4], [1, 5], [0, 5]]
[[9, 5], [9, 4], [9, 3], [8, 3], [7, 3], [7, 4], [7, 5], [6, 5], [5, 5], [5, 6], [5, 7], [4, 7], [3, 7], [2, 7], [1, 7], [1, 6], [1, 5], [0, 5]]


#### Result:
Agent can take the shortest path from any location in the environment.

Let's also try reversing the order of the shortest path

In [65]:
#display an example of reversed shortest path
path = get_shortest_path(5, 2) #go to row 5, column 2
path.reverse()
print(path)

[[0, 5], [1, 5], [1, 4], [1, 3], [1, 2], [1, 1], [2, 1], [3, 1], [3, 2], [3, 3], [4, 3], [5, 3], [5, 2]]
